spring.application.name=gestion-financiera-backend
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres.ldehgtjbakmdxqrnmqqt}
spring.datasource.password=${DATABASE_PASSWORD:4a6G449O330t4j4X}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Limitar conexiones para Supabase free tier
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000