spring.application.name=gestion-financiera-backend

server.port=8080

#spring.datasource.url=jdbc:postgresql://db.ldehgtjbakmdxqrnmqqt.supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ldehgtjbakmdxqrnmqqt
spring.datasource.password=4a6G449O330t4j4X
#spring.datasource.password=1025geronimo#
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
